language: go

go:
  - 1.7.4
  - tip

before_install:
  - go get -t -v ./...

before_script:
  - wget -O gnatsd.zip https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-linux-amd64.zip
  - unzip gnatsd.zip
  - ./gnatsd-v0.9.4-linux-amd64/gnatsd &

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
